language: python

jobs:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: osx
      osx_image: xcode11.3
      language: shell

install:
  - "pip install nose"
  - "python setup.py install"

before_script:
 - "cd test"

script:
 - "nosetests -v"
